# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/sw.el7/cmake/3.11.2/bin/cmake

# The command to remove a file.
RM = /cvmfs/sw.el7/cmake/3.11.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/t3atlas/u20mnunes/estagio_lomac_sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/t3atlas/u20mnunes/estagio_lomac_sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sw.el7/cmake/3.11.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t3atlas/u20mnunes/estagio_lomac_sim/CMakeFiles /home/t3atlas/u20mnunes/estagio_lomac_sim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t3atlas/u20mnunes/estagio_lomac_sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tile

# Build rule for target.
Tile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tile
.PHONY : Tile

# fast build rule for target.
Tile/fast:
	$(MAKE) -f CMakeFiles/Tile.dir/build.make CMakeFiles/Tile.dir/build
.PHONY : Tile/fast

#=============================================================================
# Target rules for targets named TileFCC

# Build rule for target.
TileFCC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TileFCC
.PHONY : TileFCC

# fast build rule for target.
TileFCC/fast:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/build
.PHONY : TileFCC/fast

TileFCCmain.o: TileFCCmain.cc.o

.PHONY : TileFCCmain.o

# target to build an object file
TileFCCmain.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/TileFCCmain.cc.o
.PHONY : TileFCCmain.cc.o

TileFCCmain.i: TileFCCmain.cc.i

.PHONY : TileFCCmain.i

# target to preprocess a source file
TileFCCmain.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/TileFCCmain.cc.i
.PHONY : TileFCCmain.cc.i

TileFCCmain.s: TileFCCmain.cc.s

.PHONY : TileFCCmain.s

# target to generate assembly for a file
TileFCCmain.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/TileFCCmain.cc.s
.PHONY : TileFCCmain.cc.s

src/TileFCCActionInitialization.o: src/TileFCCActionInitialization.cc.o

.PHONY : src/TileFCCActionInitialization.o

# target to build an object file
src/TileFCCActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCActionInitialization.cc.o
.PHONY : src/TileFCCActionInitialization.cc.o

src/TileFCCActionInitialization.i: src/TileFCCActionInitialization.cc.i

.PHONY : src/TileFCCActionInitialization.i

# target to preprocess a source file
src/TileFCCActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCActionInitialization.cc.i
.PHONY : src/TileFCCActionInitialization.cc.i

src/TileFCCActionInitialization.s: src/TileFCCActionInitialization.cc.s

.PHONY : src/TileFCCActionInitialization.s

# target to generate assembly for a file
src/TileFCCActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCActionInitialization.cc.s
.PHONY : src/TileFCCActionInitialization.cc.s

src/TileFCCDetectorConstruction.o: src/TileFCCDetectorConstruction.cc.o

.PHONY : src/TileFCCDetectorConstruction.o

# target to build an object file
src/TileFCCDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCDetectorConstruction.cc.o
.PHONY : src/TileFCCDetectorConstruction.cc.o

src/TileFCCDetectorConstruction.i: src/TileFCCDetectorConstruction.cc.i

.PHONY : src/TileFCCDetectorConstruction.i

# target to preprocess a source file
src/TileFCCDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCDetectorConstruction.cc.i
.PHONY : src/TileFCCDetectorConstruction.cc.i

src/TileFCCDetectorConstruction.s: src/TileFCCDetectorConstruction.cc.s

.PHONY : src/TileFCCDetectorConstruction.s

# target to generate assembly for a file
src/TileFCCDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCDetectorConstruction.cc.s
.PHONY : src/TileFCCDetectorConstruction.cc.s

src/TileFCCEventAction.o: src/TileFCCEventAction.cc.o

.PHONY : src/TileFCCEventAction.o

# target to build an object file
src/TileFCCEventAction.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCEventAction.cc.o
.PHONY : src/TileFCCEventAction.cc.o

src/TileFCCEventAction.i: src/TileFCCEventAction.cc.i

.PHONY : src/TileFCCEventAction.i

# target to preprocess a source file
src/TileFCCEventAction.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCEventAction.cc.i
.PHONY : src/TileFCCEventAction.cc.i

src/TileFCCEventAction.s: src/TileFCCEventAction.cc.s

.PHONY : src/TileFCCEventAction.s

# target to generate assembly for a file
src/TileFCCEventAction.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCEventAction.cc.s
.PHONY : src/TileFCCEventAction.cc.s

src/TileFCCFiberHit.o: src/TileFCCFiberHit.cc.o

.PHONY : src/TileFCCFiberHit.o

# target to build an object file
src/TileFCCFiberHit.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCFiberHit.cc.o
.PHONY : src/TileFCCFiberHit.cc.o

src/TileFCCFiberHit.i: src/TileFCCFiberHit.cc.i

.PHONY : src/TileFCCFiberHit.i

# target to preprocess a source file
src/TileFCCFiberHit.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCFiberHit.cc.i
.PHONY : src/TileFCCFiberHit.cc.i

src/TileFCCFiberHit.s: src/TileFCCFiberHit.cc.s

.PHONY : src/TileFCCFiberHit.s

# target to generate assembly for a file
src/TileFCCFiberHit.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCFiberHit.cc.s
.PHONY : src/TileFCCFiberHit.cc.s

src/TileFCCFiberSD.o: src/TileFCCFiberSD.cc.o

.PHONY : src/TileFCCFiberSD.o

# target to build an object file
src/TileFCCFiberSD.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCFiberSD.cc.o
.PHONY : src/TileFCCFiberSD.cc.o

src/TileFCCFiberSD.i: src/TileFCCFiberSD.cc.i

.PHONY : src/TileFCCFiberSD.i

# target to preprocess a source file
src/TileFCCFiberSD.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCFiberSD.cc.i
.PHONY : src/TileFCCFiberSD.cc.i

src/TileFCCFiberSD.s: src/TileFCCFiberSD.cc.s

.PHONY : src/TileFCCFiberSD.s

# target to generate assembly for a file
src/TileFCCFiberSD.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCFiberSD.cc.s
.PHONY : src/TileFCCFiberSD.cc.s

src/TileFCCPmtHit.o: src/TileFCCPmtHit.cc.o

.PHONY : src/TileFCCPmtHit.o

# target to build an object file
src/TileFCCPmtHit.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPmtHit.cc.o
.PHONY : src/TileFCCPmtHit.cc.o

src/TileFCCPmtHit.i: src/TileFCCPmtHit.cc.i

.PHONY : src/TileFCCPmtHit.i

# target to preprocess a source file
src/TileFCCPmtHit.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPmtHit.cc.i
.PHONY : src/TileFCCPmtHit.cc.i

src/TileFCCPmtHit.s: src/TileFCCPmtHit.cc.s

.PHONY : src/TileFCCPmtHit.s

# target to generate assembly for a file
src/TileFCCPmtHit.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPmtHit.cc.s
.PHONY : src/TileFCCPmtHit.cc.s

src/TileFCCPmtSD.o: src/TileFCCPmtSD.cc.o

.PHONY : src/TileFCCPmtSD.o

# target to build an object file
src/TileFCCPmtSD.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPmtSD.cc.o
.PHONY : src/TileFCCPmtSD.cc.o

src/TileFCCPmtSD.i: src/TileFCCPmtSD.cc.i

.PHONY : src/TileFCCPmtSD.i

# target to preprocess a source file
src/TileFCCPmtSD.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPmtSD.cc.i
.PHONY : src/TileFCCPmtSD.cc.i

src/TileFCCPmtSD.s: src/TileFCCPmtSD.cc.s

.PHONY : src/TileFCCPmtSD.s

# target to generate assembly for a file
src/TileFCCPmtSD.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPmtSD.cc.s
.PHONY : src/TileFCCPmtSD.cc.s

src/TileFCCPrimaryGeneratorAction.o: src/TileFCCPrimaryGeneratorAction.cc.o

.PHONY : src/TileFCCPrimaryGeneratorAction.o

# target to build an object file
src/TileFCCPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPrimaryGeneratorAction.cc.o
.PHONY : src/TileFCCPrimaryGeneratorAction.cc.o

src/TileFCCPrimaryGeneratorAction.i: src/TileFCCPrimaryGeneratorAction.cc.i

.PHONY : src/TileFCCPrimaryGeneratorAction.i

# target to preprocess a source file
src/TileFCCPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPrimaryGeneratorAction.cc.i
.PHONY : src/TileFCCPrimaryGeneratorAction.cc.i

src/TileFCCPrimaryGeneratorAction.s: src/TileFCCPrimaryGeneratorAction.cc.s

.PHONY : src/TileFCCPrimaryGeneratorAction.s

# target to generate assembly for a file
src/TileFCCPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCPrimaryGeneratorAction.cc.s
.PHONY : src/TileFCCPrimaryGeneratorAction.cc.s

src/TileFCCRunAction.o: src/TileFCCRunAction.cc.o

.PHONY : src/TileFCCRunAction.o

# target to build an object file
src/TileFCCRunAction.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCRunAction.cc.o
.PHONY : src/TileFCCRunAction.cc.o

src/TileFCCRunAction.i: src/TileFCCRunAction.cc.i

.PHONY : src/TileFCCRunAction.i

# target to preprocess a source file
src/TileFCCRunAction.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCRunAction.cc.i
.PHONY : src/TileFCCRunAction.cc.i

src/TileFCCRunAction.s: src/TileFCCRunAction.cc.s

.PHONY : src/TileFCCRunAction.s

# target to generate assembly for a file
src/TileFCCRunAction.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCRunAction.cc.s
.PHONY : src/TileFCCRunAction.cc.s

src/TileFCCSteppingAction.o: src/TileFCCSteppingAction.cc.o

.PHONY : src/TileFCCSteppingAction.o

# target to build an object file
src/TileFCCSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCSteppingAction.cc.o
.PHONY : src/TileFCCSteppingAction.cc.o

src/TileFCCSteppingAction.i: src/TileFCCSteppingAction.cc.i

.PHONY : src/TileFCCSteppingAction.i

# target to preprocess a source file
src/TileFCCSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCSteppingAction.cc.i
.PHONY : src/TileFCCSteppingAction.cc.i

src/TileFCCSteppingAction.s: src/TileFCCSteppingAction.cc.s

.PHONY : src/TileFCCSteppingAction.s

# target to generate assembly for a file
src/TileFCCSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCSteppingAction.cc.s
.PHONY : src/TileFCCSteppingAction.cc.s

src/TileFCCSteppingMessenger.o: src/TileFCCSteppingMessenger.cc.o

.PHONY : src/TileFCCSteppingMessenger.o

# target to build an object file
src/TileFCCSteppingMessenger.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCSteppingMessenger.cc.o
.PHONY : src/TileFCCSteppingMessenger.cc.o

src/TileFCCSteppingMessenger.i: src/TileFCCSteppingMessenger.cc.i

.PHONY : src/TileFCCSteppingMessenger.i

# target to preprocess a source file
src/TileFCCSteppingMessenger.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCSteppingMessenger.cc.i
.PHONY : src/TileFCCSteppingMessenger.cc.i

src/TileFCCSteppingMessenger.s: src/TileFCCSteppingMessenger.cc.s

.PHONY : src/TileFCCSteppingMessenger.s

# target to generate assembly for a file
src/TileFCCSteppingMessenger.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCSteppingMessenger.cc.s
.PHONY : src/TileFCCSteppingMessenger.cc.s

src/TileFCCTileHit.o: src/TileFCCTileHit.cc.o

.PHONY : src/TileFCCTileHit.o

# target to build an object file
src/TileFCCTileHit.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCTileHit.cc.o
.PHONY : src/TileFCCTileHit.cc.o

src/TileFCCTileHit.i: src/TileFCCTileHit.cc.i

.PHONY : src/TileFCCTileHit.i

# target to preprocess a source file
src/TileFCCTileHit.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCTileHit.cc.i
.PHONY : src/TileFCCTileHit.cc.i

src/TileFCCTileHit.s: src/TileFCCTileHit.cc.s

.PHONY : src/TileFCCTileHit.s

# target to generate assembly for a file
src/TileFCCTileHit.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCTileHit.cc.s
.PHONY : src/TileFCCTileHit.cc.s

src/TileFCCTileSD.o: src/TileFCCTileSD.cc.o

.PHONY : src/TileFCCTileSD.o

# target to build an object file
src/TileFCCTileSD.cc.o:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCTileSD.cc.o
.PHONY : src/TileFCCTileSD.cc.o

src/TileFCCTileSD.i: src/TileFCCTileSD.cc.i

.PHONY : src/TileFCCTileSD.i

# target to preprocess a source file
src/TileFCCTileSD.cc.i:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCTileSD.cc.i
.PHONY : src/TileFCCTileSD.cc.i

src/TileFCCTileSD.s: src/TileFCCTileSD.cc.s

.PHONY : src/TileFCCTileSD.s

# target to generate assembly for a file
src/TileFCCTileSD.cc.s:
	$(MAKE) -f CMakeFiles/TileFCC.dir/build.make CMakeFiles/TileFCC.dir/src/TileFCCTileSD.cc.s
.PHONY : src/TileFCCTileSD.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... Tile"
	@echo "... TileFCC"
	@echo "... TileFCCmain.o"
	@echo "... TileFCCmain.i"
	@echo "... TileFCCmain.s"
	@echo "... src/TileFCCActionInitialization.o"
	@echo "... src/TileFCCActionInitialization.i"
	@echo "... src/TileFCCActionInitialization.s"
	@echo "... src/TileFCCDetectorConstruction.o"
	@echo "... src/TileFCCDetectorConstruction.i"
	@echo "... src/TileFCCDetectorConstruction.s"
	@echo "... src/TileFCCEventAction.o"
	@echo "... src/TileFCCEventAction.i"
	@echo "... src/TileFCCEventAction.s"
	@echo "... src/TileFCCFiberHit.o"
	@echo "... src/TileFCCFiberHit.i"
	@echo "... src/TileFCCFiberHit.s"
	@echo "... src/TileFCCFiberSD.o"
	@echo "... src/TileFCCFiberSD.i"
	@echo "... src/TileFCCFiberSD.s"
	@echo "... src/TileFCCPmtHit.o"
	@echo "... src/TileFCCPmtHit.i"
	@echo "... src/TileFCCPmtHit.s"
	@echo "... src/TileFCCPmtSD.o"
	@echo "... src/TileFCCPmtSD.i"
	@echo "... src/TileFCCPmtSD.s"
	@echo "... src/TileFCCPrimaryGeneratorAction.o"
	@echo "... src/TileFCCPrimaryGeneratorAction.i"
	@echo "... src/TileFCCPrimaryGeneratorAction.s"
	@echo "... src/TileFCCRunAction.o"
	@echo "... src/TileFCCRunAction.i"
	@echo "... src/TileFCCRunAction.s"
	@echo "... src/TileFCCSteppingAction.o"
	@echo "... src/TileFCCSteppingAction.i"
	@echo "... src/TileFCCSteppingAction.s"
	@echo "... src/TileFCCSteppingMessenger.o"
	@echo "... src/TileFCCSteppingMessenger.i"
	@echo "... src/TileFCCSteppingMessenger.s"
	@echo "... src/TileFCCTileHit.o"
	@echo "... src/TileFCCTileHit.i"
	@echo "... src/TileFCCTileHit.s"
	@echo "... src/TileFCCTileSD.o"
	@echo "... src/TileFCCTileSD.i"
	@echo "... src/TileFCCTileSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

